# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
    npm install -g firebase-tools
    npm run build
  displayName: 'npm install and build'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- script: |
    firebase deploy --only hosting --token "1//03178dsyZQDPCCgYIARAAGAMSNwF-L9IrCr4FohVnu2q9qpyqS6v9OqveWkvE_q3JNvxsa9JwN9trn-a3HgvnQjNtk0_w6XNAFOA"
  displayName: 'firebase deployment'